/*
 * generated by Xtext 2.12.0
 */
package dk.sdu.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class WPageProposalProvider extends AbstractWPageProposalProvider {
}
