/*
 * generated by Xtext 2.12.0
 */
package dk.sdu


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WPageStandaloneSetup extends WPageStandaloneSetupGenerated {

	def static void doSetup() {
		new WPageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
