/*
 * generated by Xtext 2.12.0
 */
package dk.sdu.ide

import com.google.inject.Guice
import dk.sdu.WPageRuntimeModule
import dk.sdu.WPageStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class WPageIdeSetup extends WPageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new WPageRuntimeModule, new WPageIdeModule))
	}
	
}
